general_settings:
  name: read_manager
  display_name: Read Manager
  description: An application to manage the visual novels I read
  logo_path: assets/images/logo.png
  project_version: 0 0 0
  long_startup_process: 1
